import {useState,useSyncExternalStore} from 'react';
import type {FormEvent} from 'react';
import {PageHeader} from '../components/ui';
import {changeLocalPassword,logoutLocal,subscriptionEnd,subscriptionRemaining,accessVersion,subscribeAccess,currentSessionPassword} from '../data/localAccess';
export default function AccessSettings({theme,setTheme}:{theme:string;setTheme:(theme:'dark'|'light')=>void}){
 useSyncExternalStore(subscribeAccess,accessVersion);
 const [current,setCurrent]=useState(currentSessionPassword);const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');setSuccess('');if(password.length<4){setError('كلمة المرور الجديدة يجب ألا تقل عن 4 أحرف أو أرقام.');return;}if(password!==confirm){setError('تأكيد كلمة المرور غير مطابق.');return;}setBusy(true);try{if(!await changeLocalPassword(current,password)){setError('كلمة المرور الحالية غير صحيحة.');return;}setCurrent(password);setPassword('');setConfirm('');setSuccess('تم تغيير كلمة المرور. عليك حفظ الكلمة الجديدة؛ الإدارة لا تستطيع كشفها أو إرجاعها وهي غير مسؤولة عن فقدانها.');}catch{setError('تعذر حفظ كلمة المرور. لم يتم تأكيد التغيير.');}finally{setBusy(false);}}
 return <div className="access-settings"><nav className="breadcrumb">الحساب / الإعدادات</nav><PageHeader title="الإعدادات" description="إعدادات المظهر وكلمة المرور والاشتراك."/><section className="panel"><h2>المظهر</h2><div className="access-theme"><button className="tl-button" aria-pressed={theme==='dark'} onClick={()=>setTheme('dark')}>ليلي</button><button className="tl-button" aria-pressed={theme==='light'} onClick={()=>setTheme('light')}>نهاري</button></div></section><section className="panel"><h2>تغيير كلمة المرور</h2><p className="tl-disclaimer">تُعبّأ كلمة المرور الحالية خلال جلسة الدخول، وتُحدّث بعد نجاح التغيير. بعد إعادة تحميل الصفحة استخدم التعبئة من المتصفح أو أدخلها يدويًا.</p><form onSubmit={submit}>{[{label:'كلمة المرور الحالية',value:current,set:setCurrent,auto:'current-password'},{label:'كلمة المرور الجديدة',value:password,set:setPassword,auto:'new-password'},{label:'تأكيد كلمة المرور',value:confirm,set:setConfirm,auto:'new-password'}].map(f=><label className="tl-field" key={f.label}><span>{f.label}</span><input type="password" name={f.auto==='current-password'?'current-password':f.label==='تأكيد كلمة المرور'?'confirm-password':'new-password'} aria-label={f.label} autoComplete={f.auto} required maxLength={128} value={f.value} onChange={e=>f.set(e.target.value)}/></label>)}{error&&<p className="tl-error" role="alert">{error}</p>}{success&&<p className="tl-notice" role="status">{success}</p>}<button className="tl-button primary" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ كلمة المرور'}</button></form></section><section className="panel"><h2>الأيام المتبقية من الاشتراك</h2><p className="access-days">{subscriptionRemaining()??"—"} يوم</p><p>ينتهي الاشتراك: {new Date(subscriptionEnd()).toLocaleDateString("ar-IQ")}</p></section><button className="tl-button" onClick={logoutLocal}>تسجيل الخروج</button></div>;
}
