import {useState} from 'react';
import {FinanceModal} from '../components/FinanceViews';
import {PremiumButton} from '../components/premium/MotionUI';
import {useLocalData,updateLocal,localDate} from '../data/localStore';
import {makeInventorySale} from '../data/inventorySale';
const inventoryNumber=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n);
export function InventorySaleForm({customerId,close}:{customerId:string|null;close:()=>void}){const data=useLocalData(),[query,setQuery]=useState(''),[cart,setCart]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const customer=data.inventoryCustomers?.find(c=>c.id===customerId);const items=(data.inventory||[]).filter(i=>i.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));const total=Object.entries(cart).reduce((sum,[id,q])=>sum+(data.inventory?.find(i=>i.id===id)?.salePrice||0)*(Number(q)||0),0);function sell(){if(busy)return;setBusy(true);setError('');let applied=false;const ok=updateLocal(current=>{try{const next=makeInventorySale(current,customerId,cart,crypto.randomUUID(),localDate());applied=true;return next;}catch(e){setError(e instanceof Error?e.message:'تعذر البيع');return current;}});if(ok&&applied)close();else setBusy(false);}
return <FinanceModal title={customerId?`بيع إلى ${customer?.name||'الزبون'}`:'بيع نقدي مستقل'} close={close}><p>{customerId?'تُسجل الأسعار بالدينار العراقي ويُضاف البيع إلى دين الزبون.':'بيع نقدي بالدينار العراقي مستقل عن الصيرفة والصندوق المالي.'}</p><label className="tl-field"><span>البحث عن مادة من المخزون</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="inventory-search-results">{items.map(i=><div className="inventory-result" key={i.id}><span>{i.name}<small>المتوفر: {inventoryNumber(i.quantity)} · السعر: {inventoryNumber(i.salePrice)} IQD</small></span><PremiumButton disabled={i.quantity<=0||i.id in cart} onClick={()=>setCart(c=>({...c,[i.id]:String(Math.min(1,i.quantity))}))} aria-label={`إضافة ${i.name}`}>{i.id in cart?'مضافة':'إضافة'}</PremiumButton></div>)}{!items.length&&<p>لا توجد مواد مطابقة.</p>}</div><h3>المواد المختارة</h3>{Object.entries(cart).map(([id,value])=>{const item=data.inventory?.find(i=>i.id===id);return <div className="inventory-cart-row" key={id}><strong>{item?.name||'مادة غير متاحة'}</strong><label className="tl-field"><span>كمية {item?.name}</span><input type="number" step="0.000001" min="0.000001" max={item?.quantity||0} value={value} onChange={e=>setCart(c=>({...c,[id]:e.target.value}))}/></label><span dir="ltr">{inventoryNumber((Number(value)||0)*(item?.salePrice||0))} IQD</span><PremiumButton aria-label={`إزالة ${item?.name}`} onClick={()=>setCart(c=>{const next={...c};delete next[id];return next;})}>إزالة</PremiumButton></div>;})}<p className="inventory-total">المجموع: <b dir="ltr">{inventoryNumber(total)} IQD</b></p>{error&&<p className="tl-error" role="alert">{error}</p>}<div className="tl-modal-actions"><PremiumButton variant="primary" disabled={busy||!Object.keys(cart).length} onClick={sell}>بيع</PremiumButton><PremiumButton onClick={close}>إلغاء</PremiumButton></div></FinanceModal>;}
export function InventoryItemStats({id,close}:{id:string;close:()=>void}){const data=useLocalData();const item=data.inventory?.find(i=>i.id===id);const lines=(data.inventorySales||[]).flatMap(s=>s.lines.filter(l=>l.itemId===id).map(l=>({...l,date:s.date,customer:s.customerName})));const sold=lines.reduce((sum,l)=>sum+l.quantity,0),revenue=lines.reduce((sum,l)=>sum+l.quantity*l.salePrice,0),cost=lines.reduce((sum,l)=>sum+l.quantity*l.purchasePrice,0);return <FinanceModal title={`إحصائيات ${item?.name||'المادة'}`} close={close}><div className="inventory-stat-grid">{[['الكمية المتبقية',item?.quantity||0],['الكمية المباعة',sold],['إجمالي المبيعات · IQD',revenue],['تكلفة الشراء للمباع · IQD',cost],['الأرباح · IQD',revenue-cost]].map(([label,value])=><section className="panel inventory-item" key={label}><h3>{label}</h3><b dir="ltr">{inventoryNumber(Number(value))}</b></section>)}</div><p>الأرباح من فرق سعر البيع وتكلفة الشراء وقت البيع، قبل أي مصروفات أخرى.</p><h3>المبيعات</h3>{lines.length?lines.map((l,i)=><article className="panel inventory-item" key={i}><strong>{l.customer}</strong><p>الكمية: {inventoryNumber(l.quantity)} · سعر البيع: {inventoryNumber(l.salePrice)} IQD</p><time>{l.date.replace('T',' ')}</time></article>):<p>لا توجد مبيعات لهذه المادة بعد.</p>}</FinanceModal>;}
