import {InventoryItemStats} from './InventorySales';
import InventoryTabs from '../components/InventoryTabs';
import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import {PageHeader} from '../components/ui';
import {PremiumButton,AnimatedCard} from '../components/premium/MotionUI';
import {useLocalData,updateLocal} from '../data/localStore';
import type {InventoryItem} from '../data/localStore';
import './transferList.css';
import './inventory.css';
const number=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n);
function ItemDialog({item,remove,close}:{item?:InventoryItem;remove:boolean;close:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);const [name,setName]=useState(item?.name||'');const [quantity,setQuantity]=useState(String(item?.quantity??''));const [purchase,setPurchase]=useState(String(item?.purchasePrice??''));const [sale,setSale]=useState(String(item?.salePrice??''));const [error,setError]=useState('');
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);
 function submit(e:FormEvent){e.preventDefault();const values=[quantity,purchase,sale];if(!remove&&(!name.trim()||values.some(v=>!v.trim()||!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1e12))){setError('أدخل اسم المادة وكمية وأسعارًا صحيحة غير سالبة.');return;}
 const saved=updateLocal(data=>{const rows=data.inventory||[];if(remove)return {...data,inventory:rows.filter(r=>r.id!==item?.id)};const row={id:item?.id||crypto.randomUUID(),name:name.trim(),quantity:Number(quantity),purchasePrice:Number(purchase),salePrice:Number(sale)};return {...data,inventory:item?rows.map(r=>r.id===item.id?row:r):[...rows,row]};});if(saved)close();}
 return <dialog ref={ref} className="tl-modal inventory-dialog" aria-labelledby="inventory-dialog-title" onCancel={close}><form onSubmit={submit}><h2 id="inventory-dialog-title">{remove?'حذف المادة':item?'تعديل المادة':'إضافة مادة'}</h2>{remove?<p>هل تريد حذف «{item?.name}» من المخزون؟</p>:<div className="inventory-fields"><label className="tl-field"><span>اسم المادة</span><input autoFocus required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label>{[{label:'الكمية',value:quantity,set:setQuantity},{label:'سعر الشراء',value:purchase,set:setPurchase},{label:'سعر البيع',value:sale,set:setSale}].map(f=><label className="tl-field" key={f.label}><span>{f.label}</span><input required type="number" inputMode="decimal" min="0" max="1000000000000" step="any" value={f.value} onChange={e=>f.set(e.target.value)}/></label>)}</div>}{error&&<p role="alert" className="tl-error">{error}</p>}<div className="tl-modal-actions"><PremiumButton type="submit" variant={remove?'danger':'primary'}>{remove?'تأكيد الحذف':'حفظ'}</PremiumButton><PremiumButton type="button" onClick={close}>إلغاء</PremiumButton></div></form></dialog>;
}
export default function Inventory(){const data=useLocalData();const [dialog,setDialog]=useState<{item?:InventoryItem;remove:boolean}|null>(null);const [stats,setStats]=useState<string|null>(null);const items=data.inventory||[];return <div className="inventory-page"><InventoryTabs/><div className="inventory-heading"><PageHeader title="المخزون" description="إدارة المواد والكميات وأسعار الشراء والبيع."/><PremiumButton variant="primary" onClick={()=>setDialog({remove:false})}>إضافة مادة</PremiumButton></div>{items.length?<div className="inventory-grid">{items.map(item=><AnimatedCard className="panel inventory-item" key={item.id}><button className="inventory-customer-open" onClick={()=>setStats(item.id)}><h2>{item.name}</h2><small>عرض المبيعات والأرباح</small></button><dl>{[['الكمية',item.quantity],['سعر الشراء',item.purchasePrice],['سعر البيع',item.salePrice]].map(([label,value])=><div key={label}><dt>{label}</dt><dd dir="ltr">{number(Number(value))}</dd></div>)}</dl><div className="inventory-actions"><PremiumButton aria-label={`تعديل ${item.name}`} onClick={()=>setDialog({item,remove:false})}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="m16 3 5 5-12 12-6 1 1-6Z M14 5l5 5"/></svg>تعديل</PremiumButton><PremiumButton variant="danger" aria-label={`حذف ${item.name}`} onClick={()=>setDialog({item,remove:true})}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/></svg>حذف</PremiumButton></div></AnimatedCard>)}</div>:<section className="panel inventory-empty"><h2>لا توجد مواد في المخزون</h2><p>اضغط «إضافة مادة» لإدخال أول مادة.</p></section>}{stats&&<InventoryItemStats id={stats} close={()=>setStats(null)}/ >}{dialog&&<ItemDialog item={dialog.item} remove={dialog.remove} close={()=>setDialog(null)}/>}</div>;}
