import {InventorySaleForm} from './InventorySales';
import {useState} from 'react';
import type {FormEvent} from 'react';
import {PageHeader} from '../components/ui';
import {FinanceModal} from '../components/FinanceViews';
import {PremiumButton,AnimatedCard} from '../components/premium/MotionUI';
import InventoryTabs from '../components/InventoryTabs';
import {useLocalData,updateLocal,localDate} from '../data/localStore';
import type {InventoryCustomer} from '../data/localStore';
import {debtTotals} from '../data/inventoryLedger';
import {useCurrencies} from '../data/currencyStore';
import './inventory.css';
const number=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n);
function CustomerForm({customer,close}:{customer?:InventoryCustomer;close:()=>void}){const [name,setName]=useState(customer?.name||''),[phone,setPhone]=useState(customer?.phone||''),[details,setDetails]=useState(customer?.details||'');const [error,setError]=useState('');function save(e:FormEvent){e.preventDefault();if(!name.trim()||!phone.trim()){setError('الاسم ورقم الهاتف مطلوبان.');return;}if(updateLocal(data=>{const rows=data.inventoryCustomers||[];return {...data,inventoryCustomers:customer?rows.map(c=>c.id===customer.id?{...c,name:name.trim(),phone:phone.trim(),details}:c):[...rows,{id:crypto.randomUUID(),name:name.trim(),phone:phone.trim(),details,transactions:[]}]};}))close();}return <FinanceModal title={customer?'تعديل الزبون':'إضافة زبون'} close={close}><form onSubmit={save}><div className="inventory-fields"><label className="tl-field"><span>رقم الهاتف</span><input type="tel" required maxLength={30} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="tl-field"><span>الاسم</span><input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="tl-field"><span>التفاصيل (اختياري)</span><textarea maxLength={2000} value={details} onChange={e=>setDetails(e.target.value)}/></label></div>{error&&<p role="alert">{error}</p>}<div className="tl-modal-actions"><PremiumButton type="submit" variant="primary">حفظ</PremiumButton><PremiumButton type="button" onClick={close}>إلغاء</PremiumButton></div></form></FinanceModal>;}
function CustomerDetails({id,close}:{id:string;close:()=>void}){const data=useLocalData(),currencies=useCurrencies();const customer=data.inventoryCustomers?.find(c=>c.id===id);const [mode,setMode]=useState<'debt'|'payment'|null>(null),[amount,setAmount]=useState(''),[currency,setCurrency]=useState('IQD'),[details,setDetails]=useState(''),[error,setError]=useState('');if(!customer)return null;const totals=debtTotals(customer.transactions);const options=[...new Set([...currencies.map(c=>c.code),...Object.keys(totals)])];function save(e:FormEvent){e.preventDefault();const n=Number(amount);if(!mode||!amount.trim()||!Number.isFinite(n)||n<=0||n>1e12){setError('أدخل مبلغًا صحيحًا أكبر من صفر.');return;}if(mode==='payment'&&n>(totals[currency]||0)){setError('مبلغ التسديد أكبر من الدين بهذه العملة.');return;}const row={id:crypto.randomUUID(),date:localDate(),type:mode,currency,amount:n,details};if(updateLocal(d=>({...d,inventoryCustomers:(d.inventoryCustomers||[]).map(c=>c.id===id?{...c,transactions:[...(c.transactions||[]),row]}:c)}))){setMode(null);setAmount('');setDetails('');setError('');}}
if(mode==='debt')return <InventorySaleForm customerId={id} close={()=>setMode(null)}/>;
return <FinanceModal title={customer.name} close={close}><p dir="ltr">{customer.phone}</p>{customer.details&&<p>{customer.details}</p>}<section className="panel inventory-item"><h3>الدين الكلي</h3>{Object.keys(totals).length?Object.entries(totals).map(([code,balance])=><p key={code}><b dir="ltr">{number(balance)} {code}</b></p>):<strong>0</strong>}</section><div className="tl-modal-actions"><PremiumButton onClick={()=>{setMode('debt');setError('');}}>إضافة دين</PremiumButton><PremiumButton onClick={()=>{setMode('payment');setError('');}}>تسديد</PremiumButton></div>{mode&&<form onSubmit={save}><h3>تسديد دين</h3><div className="inventory-fields"><label className="tl-field"><span>المبلغ</span><input required type="number" min="0.000001" max="1000000000000" step="0.000001" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="tl-field"><span>العملة</span><select value={currency} onChange={e=>setCurrency(e.target.value)}>{options.map(c=><option key={c}>{c}</option>)}</select></label><label className="tl-field"><span>تفاصيل المعاملة (اختياري)</span><textarea maxLength={1000} value={details} onChange={e=>setDetails(e.target.value)}/></label></div>{error&&<p role="alert" className="tl-error">{error}</p>}<div className="tl-modal-actions"><PremiumButton type="submit" variant="primary">حفظ المعاملة</PremiumButton><PremiumButton type="button" onClick={()=>setMode(null)}>إلغاء المعاملة</PremiumButton></div></form>}<h3>المعاملات</h3>{customer.transactions?.length?<div className="inventory-transactions">{[...customer.transactions].reverse().map(t=><article className="panel inventory-item" key={t.id}><strong>{t.type==='debt'?'إضافة دين':'تسديد'}</strong><p dir="ltr">{number(t.amount)} {t.currency}</p><time>{t.date.replace('T',' ')}</time>{t.details&&<p>{t.details}</p>}</article>)}</div>:<p>لا توجد معاملات بعد.</p>}</FinanceModal>;}
export default function InventoryCustomers(){const data=useLocalData();const [action,setAction]=useState<{type:'add'|'edit'|'delete'|'view';id?:string}|null>(null);const customers=data.inventoryCustomers||[],selected=customers.find(c=>c.id===action?.id);return <div className="inventory-page"><InventoryTabs/><div className="inventory-heading"><PageHeader title="زبائن المخزون" description="بيانات الزبائن والديون والتسديدات."/><PremiumButton variant="primary" onClick={()=>setAction({type:'add'})}>إضافة زبون</PremiumButton></div><div className="inventory-grid">{customers.map(c=><AnimatedCard className="panel inventory-item" key={c.id}><button className="inventory-customer-open" onClick={()=>setAction({type:'view',id:c.id})}><h2>{c.name}</h2><span dir="ltr">{c.phone}</span><small>عرض الدين والمعاملات</small></button><div className="inventory-actions"><PremiumButton aria-label={`تعديل ${c.name}`} onClick={()=>setAction({type:'edit',id:c.id})}>✎ تعديل</PremiumButton><PremiumButton variant="danger" aria-label={`حذف ${c.name}`} onClick={()=>setAction({type:'delete',id:c.id})}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/></svg>حذف</PremiumButton></div></AnimatedCard>)}</div>{!customers.length&&<section className="panel inventory-empty"><h2>لا يوجد زبائن بعد</h2><p>اضغط «إضافة زبون» للبدء.</p></section>}{action?.type==='add'&&<CustomerForm close={()=>setAction(null)}/ >}{action?.type==='edit'&&selected&&<CustomerForm customer={selected} close={()=>setAction(null)}/ >}{action?.type==='view'&&selected&&<CustomerDetails id={selected.id} close={()=>setAction(null)}/ >}{action?.type==='delete'&&selected&&<FinanceModal title="حذف الزبون" close={()=>setAction(null)}><p>سيُحذف «{selected.name}» وجميع ديونه ومعاملاته ({selected.transactions?.length||0} معاملة). لا يمكن التراجع عن الحذف.</p><div className="tl-modal-actions"><PremiumButton variant="danger" onClick={()=>{if(updateLocal(d=>({...d,inventoryCustomers:(d.inventoryCustomers||[]).filter(c=>c.id!==selected.id)})))setAction(null);}}>تأكيد الحذف</PremiumButton><PremiumButton onClick={()=>setAction(null)}>إلغاء</PremiumButton></div></FinanceModal>}</div>;}
